import React from 'react';
import {act,create} from 'react-test-renderer';
import {afterEach,it,expect,vi} from 'vitest';
vi.mock('../../../api/client/documentsSendings',()=>({fetchPlanDateQueue:vi.fn(),resumePlanDateQueue:vi.fn()}));
import {fetchPlanDateQueue} from '../../../api/client/documentsSendings';
import {PlanDateQueueProvider,SendingPlanDateProgress} from './PlanDateQueueStatus';
let root:ReturnType<typeof create>;
afterEach(()=>{act(()=>root?.unmount());vi.useRealTimers();vi.unstubAllGlobals();vi.clearAllMocks();});
it('renders details only when opened and polls idle queues once per minute',async()=>{
 vi.useFakeTimers();vi.stubGlobal('document',{hidden:false});vi.stubGlobal('window',{addEventListener:vi.fn(),removeEventListener:vi.fn()});
 vi.mocked(fetchPlanDateQueue).mockResolvedValue([{cargo_number:'000142716',target_date:'2026-09-30',state:'done'}]);
 const row={CargoNumber:'000142716'};
 await act(async()=>{root=create(React.createElement(PlanDateQueueProvider,{auth:{login:'staff',password:'fixture'},rows:[row],children:React.createElement(SendingPlanDateProgress,{row,fallback:'нет'})}));});
 expect(fetchPlanDateQueue).toHaveBeenCalledTimes(1);
 expect(root.root.findAllByProps({className:'sending-plan-progress__entry sending-plan-progress__entry--done'})).toHaveLength(0);
 await act(async()=>root.root.findByType('details').props.onToggle({currentTarget:{open:true}}));
 expect(JSON.stringify(root.toJSON())).toContain('30.09.2026');
 await act(async()=>vi.advanceTimersByTime(30000));
 expect(fetchPlanDateQueue).toHaveBeenCalledTimes(1);
 await act(async()=>vi.advanceTimersByTime(30000));
 expect(fetchPlanDateQueue).toHaveBeenCalledTimes(2);
});
