import type React from "react";
import type { SanctionCheckResult } from "../../../lib/sanctions";
import type { SendingsRowRuntime } from "./sendingsRowRuntime";
import type { EorStatus } from "./sendingsTypes";
import type { AuthData, CargoItem } from "../../../types";

export type SendingsSectionProps = {
  tableModeEffective: any;
  docsMotionEnabled: any;
  cargoModeSwitchMotion: any;
  canSelectSendingRows: any;
  allVisibleSendingsSelected: any;
  visibleSendingMeta: any;
  setSelectedSendingRowKeys: React.Dispatch<React.SetStateAction<Set<string>>>;
  selectedSendingRowKeys: Set<string>;
  handleSendingsSort: (column: "date" | "number" | "route" | "type" | "transitHours" | "vehicle" | "comment" | "paidWeight" | "cost" | "declaredCost") => void;
  sendingsSortColumn: any;
  sendingsSortOrder: any;
  hasAnalytics: any;
  showSums: any;
  showEorColumn: any;
  canEditEor: any;
  canEditPlanDate: any;
  canRunSanctionsCheck: any;
  sendingRowsSorted: any;
  sendingsRowRuntime: SendingsRowRuntime;
  normalizeTransportDisplay: any;
  effectiveSearchText: any;
  expandedSendingRow: any;
  setExpandedSendingRow: React.Dispatch<React.SetStateAction<string | null>>;
  cargoSumByNumber: any;
  sendingSanctionMap: Record<string, SanctionCheckResult>;
  eorStatusMap: any;
  ferriesList: any;
  sendingsFerryMap: any;
  ferryEtaLoadingByRow: any;
  handleFerrySelect: (rowKey: string, ferryIdStr: string, effectiveInn: string | null) => Promise<void>;
  effectiveActiveInn: any;
  getSendingsFerryEntry: any;
  onOpenAisWithMmsi: (mmsi: string) => void;
  onOpenCargo: (cargoNumber: string, prefetchedItem?: CargoItem) => void;
  perevozkiItems?: CargoItem[];
  sendingsDetailsView: any;
  setSendingsDetailsView: React.Dispatch<React.SetStateAction<"general" | "byCargo" | "byCustomer">>;
  sendingsSummaryGroupBy: any;
  setSendingsSummaryGroupBy: React.Dispatch<React.SetStateAction<"customer" | "receiver">>;
  sendingsSummarySortColumn: any;
  sendingsSummarySortOrder: any;
  handleSendingsSummarySort: (column: "index" | "cargo" | "status" | "count" | "volume" | "weight" | "paidWeight" | "cost" | "customer" | "density") => void;
  cargoStateByNumber: any;
  cargoPlanDateByNumber: Map<string, string>;
  cargoReceiverByNumber: any;
  cargoCustomerByNumber: any;
  showCustomerColumn: any;
  effectiveServiceMode: any;
  selectedByCustomerSummaryKeys: any;
  setSelectedByCustomerSummaryKeys: React.Dispatch<React.SetStateAction<Set<string>>>;
  expandedByCustomerKey: any;
  setExpandedByCustomerKey: React.Dispatch<React.SetStateAction<string | null>>;
  byCustomerPlanDateOpen: any;
  setByCustomerPlanDateOpen: React.Dispatch<React.SetStateAction<boolean>>;
  byCustomerPlanDateValue: any;
  setByCustomerPlanDateValue: React.Dispatch<React.SetStateAction<string>>;
  byCustomerActionLoading: any;
  setByCustomerActionLoading: React.Dispatch<React.SetStateAction<boolean>>;
  byCustomerActionError: any;
  setByCustomerActionError: React.Dispatch<React.SetStateAction<string | null>>;
  byCustomerActionInfo: any;
  setByCustomerActionInfo: React.Dispatch<React.SetStateAction<string | null>>;
  selectedVisibleSendingCount: any;
  bulkSendingActionLoading: any;
  bulkEorMenuOpen: any;
  setBulkEorMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  bulkPlanDateOpen: any;
  setBulkPlanDateOpen: React.Dispatch<React.SetStateAction<boolean>>;
  bulkPlanDateValue: any;
  setBulkPlanDateValue: React.Dispatch<React.SetStateAction<string>>;
  bulkSendingActionError: any;
  bulkSendingActionInfo: any;
  applyBulkEorStatus: (status: EorStatus) => void;
  applyBulkPlanDate: () => void;
  applyBulkSanctionsCheck: () => void;
  applyByCustomerPlanDate: (cargoNumbers: string[], groupBy: "customer" | "receiver") => Promise<void>;
  auth: AuthData | null | undefined;
};

export type SendingsSectionViewProps = SendingsSectionProps & {
  handleOpenCargo: (cargoNumber: string, partial?: Partial<CargoItem>) => void;
};
