import {readFileSync,mkdirSync,writeFileSync,copyFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {htmlEscape as e} from '../lib/mediaMarketing/contentHtml.js';
import {markdownToSafeHtml} from '../lib/mediaMarketing/safePublicMarkdown.js';
import {collectFacts,resultIssues} from '../lib/mediaMarketing/factorySources.js';
const pack=JSON.parse(readFileSync('docs/pilot/t09-2026-10-01.json','utf8'));
const dir=resolve(process.argv[2]||'/tmp/haulz-t09-preview');mkdirSync(dir,{recursive:true});
// Palette: src/styles/modules/guest-shadcn.css (public home page).
// Match the home page wordmark (GuestHomePage / guest-home-hero__brand).
copyFileSync(resolve('node_modules/@fontsource/manrope/files/manrope-latin-800-normal.woff2'),resolve(dir,'manrope-latin-800-normal.woff2'));
const css=`@font-face{font-family:Manrope;font-style:normal;font-weight:800;font-display:swap;src:url('/manrope-latin-800-normal.woff2') format('woff2')}*{box-sizing:border-box}body{margin:0;background:#f3f4f6;color:#1f2937;font:17px/1.7 system-ui,sans-serif}a{color:#2563eb}a:focus-visible,button:focus-visible,summary:focus-visible{outline:3px solid #2563eb;outline-offset:4px}header,main,footer{max-width:1180px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;border-bottom:1px solid #e5e7eb;gap:20px}.logo{font-family:"Manrope","DM Sans",system-ui,sans-serif;font-size:30px;font-weight:800;letter-spacing:0.08em;line-height:0.92;text-transform:uppercase;color:#1f2937;text-decoration:none}.tag{font:12px/1.5 system-ui;letter-spacing:1.5px;text-transform:uppercase;color:#6b7280}h1{font-size:clamp(32px,6vw,64px);line-height:1.1;letter-spacing:-2px;max-width:940px}h2{font-size:26px;line-height:1.25;margin-top:36px}p{max-width:800px}.intro{font-size:21px;line-height:1.6;color:#4b5563}.notice{background:#0f1c33;color:#fff;padding:12px 24px;font-size:14px}.notice a{color:#ffffff}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin:32px 0}.card{background:white;padding:28px;border:1px solid #e5e7eb;border-radius:18px}.card h2{margin:12px 0}.pill{display:inline-block;border:1px solid #e5e7eb;border-radius:99px;font-size:13px;padding:4px 10px}.path{font:13px/1.5 ui-monospace,monospace;overflow-wrap:anywhere;color:#4b5563}.layout{display:grid;grid-template-columns:minmax(0,800px) 230px;gap:52px}.body{overflow-wrap:anywhere}aside{border-left:1px solid #e5e7eb;padding-left:22px;font-size:14px}aside p{color:#4b5563}details{border-bottom:1px solid #e5e7eb;padding:18px 0}summary{cursor:pointer;font-weight:650}.cta{display:inline-block;background:#2563eb;color:#ffffff;border-radius:12px;padding:14px 22px;text-decoration:none;font-weight:700}.meta{font-size:14px;color:#4b5563}.review{padding:18px 22px;background:#eff6ff;border-radius:12px;margin:24px 0}.review p{margin:6px 0}.table{overflow:auto}table{border-collapse:collapse;font-size:14px;width:100%}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #e5e7eb;padding:10px}footer{border-top:1px solid #e5e7eb;font-size:14px}nav{display:flex;gap:16px;flex-wrap:wrap}@media(max-width:760px){.grid,.layout{grid-template-columns:1fr}.layout{gap:20px}aside{border-left:0;border-top:1px solid #e5e7eb;padding:20px 0}header,main,footer{padding:20px}.card{padding:22px}h1{letter-spacing:-1px}.intro{font-size:18px}}`;
const wrap=(title:string,body:string)=>`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${e(title)} — пилот HAULZ</title><style>${css}</style></head><body><div class="notice">Редакционный предпросмотр · новые тексты не опубликованы · <a href="/index.html">Все восемь материалов</a></div><header><a class="logo" href="/index.html">HAULZ</a><span class="tag">Пилот / 01 октября 2026</span></header>${body}<footer>Публикация — после приёмки владельцем. Предпросмотр не отправляет заявки, не запускает генерацию и не собирает аналитику.</footer></body></html>`;
const report:any={date:'2026-10-01',materials:[],paid_generation_calls:0,provider_cost_usd:0,owner_approved:false};
const seen=new Set<string>();
for(const m of pack.materials){
 if(seen.has(m.canonical_path))throw Error('Duplicate URL');seen.add(m.canonical_path);
 const body=m.sections.map((s:any)=>`## ${s.title}\n${s.text}`).join('\n\n')+'\n\n## Вопросы и ответы\n'+m.questions.map((q:any)=>`### ${q.question}\n${q.answer}`).join('\n\n');
 const facts=await collectFacts(m.fact_ids);const errors=resultIssues({body_markdown:body,meta_description:m.description,article_title:m.title},facts);
 const unknown=[...m.sections,...m.questions].flatMap((x:any)=>x.fact_ids).filter((id:string)=>!m.fact_ids.includes(id));if(unknown.length)errors.push('Unlisted facts: '+unknown.join());
 report.materials.push({id:m.id,path:m.canonical_path,mode:m.mode,errors,fact_ids:m.fact_ids,sources:facts.sources,registry_hash:facts.registry_hash,word_count:(m.answer+' '+body).split(/\s+/).length,title_length:m.title.length,description_length:m.description.length});
 const sectionHtml=m.sections.map((s:any)=>`<section id="${e(s.id)}"><h2>${e(s.title)}</h2>${markdownToSafeHtml(s.text)}</section>`).join('');
 const faq=m.questions.map((q:any)=>`<details><summary>${e(q.question)}</summary><p>${e(q.answer)}</p></details>`).join('');
 const action=m.id==='P06'?['/sklady','Обсудить условия полной загрузки']:['/kalkulyator','Рассчитать перевозку'];
 const article=`<main><p class="tag">${e(m.id)} / ${m.mode==='new'?'Новая страница услуги':'Обновление существующей страницы'}</p><p class="path">${e(m.canonical_path)}</p><h1>${e(m.title)}</h1><p class="intro">${e(m.answer)}</p><div class="review"><p><strong>Изменение для приёмки</strong></p><p>${e(m.editorial_change)}</p>${m.id==='P08'?'<p>Это предпросмотр поясняющего текста. Действующий калькулятор остаётся на сайте.</p>':''}<p>Предлагаемая подпись: ${e(pack.author_name||'ожидает выбора владельца')}. Срок проверки фактов: до 31 октября.</p></div><div class="layout"><article class="body">${sectionHtml}<section><h2>Вопросы и ответы</h2>${faq}</section><p><a class="cta" href="https://haulz.space${action[0]}" target="_blank" rel="noreferrer">${action[1]} ↗</a></p></article><aside><strong>Редакционная карточка</strong><p>Группы спроса: ${e(m.demand_groups.join(', '))}</p><p>Описание для поиска:<br>${e(m.description)}</p><details><summary>Основа утверждений</summary>${facts.facts.map(f=>`<p><strong>${e(f.id)}</strong><br>${e(f.claim)}</p>`).join('')}</details><p>Техническая проверка: ${errors.length?e(errors.join('; ')):'пройдена'}. Смысл и полноту текста проверяет владелец.</p></aside></div><nav>${pack.materials.map((x:any)=>`<a href="/${x.id}.html"${x.id===m.id?' aria-current="page"':''}>${x.id}</a>`).join('')}</nav></main>`;
 writeFileSync(resolve(dir,`${m.id}.html`),wrap(m.title,article));
}
const cards=pack.materials.map((m:any)=>`<article class="card"><span class="pill">${m.mode==='new'?'Новая услуга':'Обновление'}</span><p class="tag">${m.id} · ${m.demand_groups.join(' / ')}</p><h2><a href="/${m.id}.html">${e(m.title)}</a></h2><p class="path">${e(m.canonical_path)}</p><p>${e(m.editorial_change)}</p><a href="/${m.id}.html">Читать и проверить →</a></article>`).join('');
writeFileSync(resolve(dir,'index.html'),wrap('Восемь материалов для редакционной приёмки',`<main><p class="tag">T09 / версия ${e(String(pack.version))}</p><h1>От запроса — к понятной отправке.</h1><p class="intro">Восемь материалов по карте спроса: три новые страницы услуг и пять обновлений. Подготовлены на подтверждённых фактах HAULZ.</p><p>Все тексты доступны по карточкам ниже. Для приёмки отметьте номера материалов, которые подходят, и правки к остальным. Предлагаемая подпись: <strong>${e(pack.author_name||'ожидает подтверждения')}</strong>.</p><div class="grid">${cards}</div><section class="review"><h2>Что входит в приёмку</h2><p>Проверьте, правильно ли описаны услуги и подготовка отправки; нет ли обязательных условий, которые следует добавить. Новые цены, сроки, адреса, контакты и особые условия в пилот не включены.</p><p>Статья о таможенных документах ждёт проверки официальных требований и эксперта. Текущий пакет не содержит юридических рекомендаций.</p><p>Платных вызовов генерации: 0. Это не оценка полной стоимости работы: стоимость текущей сессии и время владельца не измерены.</p></section></main>`));
writeFileSync('docs/audits/seo-t09-drafts-2026-10-01.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({dir,materials:report.materials.length,errors:report.materials.flatMap((x:any)=>x.errors.map((e:string)=>x.id+': '+e))}));
