import type { ServiceContent } from './serviceContent.js';
import { htmlEscape as e, jsonLdScript, displayDate } from './contentHtml.js';
export function publicServiceHtml(service: ServiceContent, preview = false): string {
 const canonical=`https://haulz.space/uslugi/${encodeURIComponent(service.slug)}`;
 const cta=service.cta||{path:'/kalkulyator',label:'Рассчитать перевозку'};
 const action=`<a class="action" href="${e(cta.path)}">${e(cta.label)}</a>`;
 const schema={'@context':'https://schema.org','@type':'Service',name:service.title,description:service.answer,url:canonical,provider:{'@type':'Organization',name:'HAULZ',url:'https://haulz.space/'}};
 const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(service.seoTitle||service.title+' | HAULZ')}</title><meta name="description" content="${e(service.description)}"><meta name="robots" content="${preview?'noindex, nofollow':'index, follow'}">${preview?'':`<link rel="canonical" href="${canonical}">${jsonLdScript(schema)}<script type="module" src="/public-analytics.js"></script>`}<meta property="og:title" content="${e(service.title)}"><meta property="og:description" content="${e(service.description)}"><meta property="og:url" content="${canonical}"><meta property="og:type" content="website"><style>
@font-face{font-family:Manrope;src:url('/fonts/manrope-latin-400-normal.woff2') format('woff2');font-weight:400;font-display:swap;}@font-face{font-family:Manrope;src:url('/fonts/manrope-latin-800-normal.woff2') format('woff2');font-weight:800;font-display:swap;}@font-face{font-family:Manrope;src:url('/fonts/manrope-cyrillic-400-normal.woff2') format('woff2');font-weight:400;font-display:swap;unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:Manrope;src:url('/fonts/manrope-cyrillic-800-normal.woff2') format('woff2');font-weight:800;font-display:swap;unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}
*{box-sizing:border-box}body{margin:0;background:#f3f4f6;color:#1f2937;font-family:Manrope,system-ui,sans-serif;line-height:1.7}a{color:#2563eb}header,main,footer{max-width:1120px;margin:auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;gap:20px}.logo{font-size:30px;font-weight:800;letter-spacing:.08em;color:#1f2937;text-decoration:none}h1{font-size:clamp(32px,5vw,64px);line-height:1.12;letter-spacing:-.035em;max-width:950px;margin:28px 0}h2{font-size:26px;line-height:1.3}.eyebrow{color:#2563eb;font-size:13px;letter-spacing:.13em;font-weight:800;margin-top:40px}.intro{font-size:19px;max-width:850px;color:#4b5563}.action{display:inline-block;padding:14px 22px;background:#2563eb;color:white;text-decoration:none;border-radius:12px;font-weight:700;margin-top:12px}.grid{display:grid;grid-template-columns:220px minmax(0,1fr);gap:48px;margin-top:64px}.toc{position:sticky;top:24px;align-self:start}.toc a{display:block;margin:12px 0;text-decoration:none;font-size:14px}.body{background:white;border:1px solid #e5e7eb;border-radius:24px;padding:32px}.body section{padding-bottom:24px;border-bottom:1px solid #e5e7eb;scroll-margin-top:24px}.body p{color:#4b5563}details{padding:16px 0;border-bottom:1px solid #e5e7eb}summary{cursor:pointer;font-weight:700}.related,footer{display:flex;flex-wrap:wrap;gap:20px}.related{margin-top:32px}.meta{font-size:13px}.preview{padding:14px;background:#dbeafe;text-align:center}footer{margin-top:30px;border-top:1px solid #e5e7eb}a:focus-visible,summary:focus-visible{outline:3px solid #2563eb;outline-offset:4px}@media(max-width:700px){.grid{grid-template-columns:1fr;gap:16px;margin-top:32px}.toc{position:static}.body{padding:20px}header,main,footer{padding:20px}header>a:last-child{font-size:13px}h2{font-size:23px}}
</style></head><body>${preview?'<div class="preview">Черновик для согласования · на сайте не опубликован</div>':''}<header><a class="logo" href="/">HAULZ</a>${action}</header><main><nav aria-label="Хлебные крошки"><a href="/">Главная</a> / Услуги</nav><p class="eyebrow">ДЛЯ БИЗНЕСА · МОСКВА ↔ КАЛИНИНГРАД</p><h1>${e(service.title)}</h1><p class="intro">${e(service.answer)}</p>${action}<div class="grid"><nav class="toc" aria-label="На этой странице"><strong>Об услуге</strong>${service.sections.map(s=>`<a href="#${e(s.id)}">${e(s.title)}</a>`).join('')}<a href="#questions">Вопросы и ответы</a></nav><div class="body">${service.sections.map(s=>`<section id="${e(s.id)}"><h2>${e(s.title)}</h2>${s.text.split('\n\n').map(p=>`<p>${e(p)}</p>`).join('')}</section>`).join('')}<section id="questions"><h2>Перед отправкой</h2>${service.questions.map(q=>`<details><summary>${e(q.question)}</summary><p>${e(q.answer)}</p></details>`).join('')}</section><nav class="related" aria-label="Полезные страницы">${(service.related||[]).map(link=>`<a href="${e(link.path)}">${e(link.title)}</a>`).join('')}</nav><p class="meta">Редакция HAULZ · Проверено ${e(displayDate(service.reviewedAt)||service.reviewedAt)}. Условия конкретного груза уточняются при оформлении.</p>${action}</div></div></main><footer><a href="/faq">Вопросы и ответы</a><a href="/sklady">Склады и контакты</a><a href="/blog">Блог</a><a href="/o-kompanii">О компании</a></footer></body></html>`;
 return preview?html.replace(/href="\/(?!\/)/g,'href="https://haulz.space/'):html;
}
