import type { ServiceContent } from './serviceContent.js';
import { htmlEscape as e, jsonLdScript, displayDate } from './contentHtml.js';
import { publicBlogStyles } from './publicBlogStyles.js';
export function publicServiceHtml(service: ServiceContent, preview = false): string {
  const canonical = `https://haulz.space/uslugi/${encodeURIComponent(service.slug)}`;
  const sections = service.sections.map(s => `<section id="${e(s.id)}"><h2>${e(s.title)}</h2><p>${e(s.text)}</p>${s.id === 'directions' ? '<div class="routes"><a href="/perevozka-moskva-kaliningrad">Москва → Калининград ↗</a><a href="/perevozka-kaliningrad-moskva">Калининград → Москва ↗</a></div>' : ''}</section>`).join('');
  const schema = { '@context': 'https://schema.org', '@type': 'Service', name: service.title, description: service.answer, url: canonical, provider: { '@type': 'Organization', name: 'HAULZ', url: 'https://haulz.space/' } };
  const html = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(service.title)} | HAULZ</title><meta name="description" content="${e(service.description)}"><meta name="robots" content="${preview ? 'noindex, nofollow' : 'index, follow'}">${preview ? '' : `<link rel="canonical" href="${canonical}">${jsonLdScript(schema)}<script type="module" src="/public-analytics.js"></script>`}<meta property="og:title" content="${e(service.title)}"><meta property="og:description" content="${e(service.description)}"><meta property="og:type" content="website"><style>${publicBlogStyles}
main{max-width:1120px}h1{max-width:850px;font-size:clamp(40px,7vw,76px);letter-spacing:-3px}.intro{max-width:760px}.grid{display:grid;grid-template-columns:220px minmax(0,1fr);gap:64px;margin-top:64px}.toc{position:sticky;top:24px;align-self:start}.toc a{display:block;margin:12px 0;text-decoration:none;font-size:14px;color:#586773}.body section{padding:0 0 30px;border-bottom:1px solid #d8ddd7;scroll-margin-top:24px}.body h2{margin-top:28px}.routes{display:flex;flex-wrap:wrap;gap:16px}.routes a{padding:12px 16px;background:#e9ede8;border-radius:10px;font-size:14px;text-decoration:none}.pill{display:inline-block;border:1px solid #ccd3ce;border-radius:99px;padding:6px 12px;font-size:13px}.action{display:inline-block;padding:14px 22px;background:#d4fa65;color:#142c3d;text-decoration:none;border-radius:12px;font-weight:bold;margin-top:12px}.preview{padding:14px 24px;background:#fff2c7;text-align:center;font-size:14px}details{padding:18px 0;border-bottom:1px solid #d8ddd7}summary{cursor:pointer;font-weight:bold}details p{color:#586773}.meta{font-size:13px;color:#586773}header,footer{max-width:1120px}@media(max-width:700px){.grid{grid-template-columns:1fr;gap:12px;margin-top:36px}.toc{position:static;border-bottom:1px solid #d8ddd7;padding-bottom:20px}h1{letter-spacing:-1.5px}.routes{flex-direction:column}}
</style></head><body>${preview ? '<div class="preview">Черновик для согласования · на сайте не опубликован</div>' : ''}<header><a class="logo" href="/">HAULZ ↗</a><a href="/kalkulyator">Рассчитать перевозку</a></header><main><nav aria-label="Хлебные крошки"><a href="/">Главная</a> / Услуга</nav><p class="eyebrow">МОСКВА ↔ КАЛИНИНГРАД</p><h1>${e(service.title)}</h1><p class="intro">${e(service.answer)}</p><span class="pill">Забор и доставка до адреса</span><br><a class="action" href="/kalkulyator">Рассчитать мой груз ↗</a><div class="grid"><nav class="toc" aria-label="На этой странице"><strong>Об услуге</strong>${service.sections.map(s => `<a href="#${e(s.id)}">${e(s.title)}</a>`).join('')}<a href="#questions">Вопросы и ответы</a></nav><div class="body">${sections}<section id="questions"><h2>Перед отправкой</h2>${service.questions.map(q => `<details><summary>${e(q.question)}</summary><p>${e(q.answer)}</p></details>`).join('')}</section><p class="meta">HAULZ · Доступность услуги проверена ${e(displayDate(service.reviewedAt) || service.reviewedAt)} Условия конкретного груза уточняются при оформлении.</p><aside class="cta"><p>Начните с параметров груза</p><p>Выберите направление и условия доставки, чтобы получить предварительный расчёт.</p><a href="/kalkulyator">Перейти к расчёту ↗</a></aside></div></div></main><footer><a href="/faq">Вопросы и ответы</a><a href="/sklady">Склады</a><a href="/blog">Блог</a><a href="/o-kompanii">О компании</a></footer></body></html>`;
  return preview ? html.replace(/href="\/(?!\/)/g, 'href="https://haulz.space/') : html;
}
