import type { PublicBlogArticle } from './blogArticles.js';
import { markdownToSafeHtml } from './safePublicMarkdown.js';
const escape = (s: string) => s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
export function publicBlogHtml(article: PublicBlogArticle): string {
 const title = escape(article.title); const description = escape(article.meta_description || '');
 const canonical = `https://haulz.space/blog/${encodeURIComponent(article.slug.toLowerCase())}`;
 return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — HAULZ</title><meta name="description" content="${description}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}"><meta property="og:type" content="article"><script type="module" src="/public-analytics.js"></script><style>
*{box-sizing:border-box}body{margin:0;background:#f5f6f2;color:#142c3d;font:17px/1.75 Arial,sans-serif}a{color:#2859c5}a:focus-visible{outline:3px solid #2859c5;outline-offset:5px}header,main,footer{max-width:880px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #d8ddd7}.logo{font-size:28px;letter-spacing:-1.5px;font-weight:900;color:#142c3d;text-decoration:none}main{padding-top:48px;padding-bottom:60px}h1{font-size:clamp(30px,5vw,52px);line-height:1.12;letter-spacing:-1.5px;margin:20px 0}h2,h3{line-height:1.3;margin-top:36px}h2{font-size:28px}h3{font-size:22px}.intro{font-size:20px;color:#586773}.body{overflow-wrap:anywhere}.body pre{overflow:auto;padding:20px;background:#e9ede8;border-radius:12px}.body a{word-break:break-word}.cta{margin-top:44px;padding:28px;background:#142c3d;color:#fff;border-radius:20px}.cta a{display:inline-block;color:#142c3d;background:#d4fa65;padding:12px 20px;border-radius:10px;text-decoration:none;font-weight:bold}footer{border-top:1px solid #d8ddd7;display:flex;gap:24px;flex-wrap:wrap;font-size:14px}.eyebrow{font-size:12px;letter-spacing:2px;color:#586773}@media(max-width:600px){header,main,footer{padding-left:20px;padding-right:20px}main{padding-top:30px}header{font-size:13px}.intro{font-size:17px}}
</style></head><body><header><a class="logo" href="/">HAULZ ↗</a><a href="/blog">← Все статьи</a></header><main><article><p class="eyebrow">HAULZ · БЛОГ</p><h1>${title}</h1>${description ? `<p class="intro">${description}</p>` : ''}<div class="body">${markdownToSafeHtml(article.body_markdown)}</div></article><aside class="cta"><p>Москва ↔ Калининград</p><p>Рассчитайте стоимость перевозки вашего груза.</p><a href="/kalkulyator">Рассчитать перевозку ↗</a></aside></main><footer><a href="/">Главная</a><a href="/sklady">Склады</a><a href="/faq">Вопросы и ответы</a></footer></body></html>`;
}
