import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Activity, ArrowRight, ArrowUpRight, BarChart3, BookOpen, Check, CheckCircle2, Copy, Download, Flag, Layers3, ListChecks, Loader2, Network, RefreshCw, Search, ShieldAlert, Target } from "lucide-react";
import { fetchMediaProgram, patchMediaProgramChannel, patchMediaProgramTask } from "../../../api/client/admin/mediaProgram";
import type { ProgramActivity, ProgramChannelPatch, ProgramDashboard, ProgramTask, ProgramTaskPatch, ProgramTaskStatus, ProgramTrack } from "../../../../lib/mediaMarketing/programTypes";
import { ProgramTaskDetail } from "../components/growthProgram/ProgramTaskDetail";
import { ProgramChannels } from "../components/growthProgram/ProgramChannels";
import { ProgramMap } from "../components/growthProgram/ProgramMap";
import { CHANNEL_STATUS, CONTEXT_PATH, downloadProgramDocument, exportContext, formatDate, initialProgramUi, progress, STATUS, TRACKS, UI_STORAGE_KEY, VIEWS } from "../components/growthProgram/programUi";
import "../components/growthProgram/growthProgram.css";

type Props = { adminToken: string; onNavigateMedia?: (tab: "checklist" | "mediaplan" | "ads") => void };
type TaskDraft = ProgramTaskPatch & { expected_updated_at: string | null };
type ChannelDraft = ProgramChannelPatch & { expected_updated_at: string | null };
const STATUS_ORDER: ProgramTaskStatus[] = ["done", "in_progress", "review", "blocked", "planned"];

function ActivityList({ activity, tasks, onSelect }: { activity: ProgramActivity[]; tasks: ProgramTask[]; onSelect: (id: string) => void }) {
  return activity.length ? <ol className="gp-activity-list">{activity.map((item) => {
    const statuses = item.entity_type === "task" ? STATUS : CHANNEL_STATUS;
    const label = (value: string) => (statuses as Record<string, string>)[value] ?? value;
    return <li key={item.id}><span className={`gp-activity-dot gp-status-${item.to_status}`} /><div>{item.entity_type === "task" && tasks.some((task) => task.id === item.entity_id) ? <button type="button" className="gp-text-button" onClick={() => onSelect(item.entity_id)}>{item.title}<ArrowUpRight size={13} /></button> : <strong>{item.title}</strong>}<p>{item.from_status ? `${label(item.from_status)} → ` : ""}{label(item.to_status)}</p>{item.note && <p className="gp-activity-note">{item.note}</p>}<small>{formatDate(item.created_at)} · {item.created_by || "Администратор"}</small></div></li>;
  })}</ol> : <div className="gp-empty gp-empty-small"><Activity size={24} /><h3>История начнётся с первого изменения</h3><p>Здесь будут сохранённые действия команды по задачам и каналам.</p></div>;
}

export function AdminGrowthProgramPanel({ adminToken, onNavigateMedia }: Props) {
  const [data, setData] = useState<ProgramDashboard | null>(null);
  const [ui, setUi] = useState(initialProgramUi);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [copied, setCopied] = useState(false);
  const [mutating, setMutating] = useState(false);
  const [taskDrafts, setTaskDrafts] = useState<Record<string, TaskDraft>>({});
  const [channelDrafts, setChannelDrafts] = useState<Record<string, ChannelDraft>>({});
  const requestVersion = useRef(0);
  const mutationActive = useRef(false);
  const load = useCallback(async (force = false) => {
    if (mutationActive.current && !force) return;
    const version = ++requestVersion.current;
    setLoading(true); setError("");
    try { const next = await fetchMediaProgram(adminToken); if (version === requestVersion.current) setData(next); }
    catch (cause) { if (version === requestVersion.current) setError(cause instanceof Error ? cause.message : "Не удалось загрузить программу"); }
    finally { if (version === requestVersion.current) setLoading(false); }
  }, [adminToken]);
  useEffect(() => { setData(null); setTaskDrafts({}); setChannelDrafts({}); void load(true); return () => { requestVersion.current += 1; }; }, [load]);
  useEffect(() => {
    try { localStorage.setItem(UI_STORAGE_KEY, JSON.stringify(ui)); } catch { /* The server remains the source of task progress. */ }
    const url = new URL(window.location.href);
    url.searchParams.set("media_view", ui.view);
    if (ui.selected) url.searchParams.set("program_task", ui.selected); else url.searchParams.delete("program_task");
    window.history.replaceState(window.history.state, "", url);
  }, [ui]);
  useEffect(() => { if (!notice && !copied) return; const timer = setTimeout(() => { setNotice(""); setCopied(false); }, 3000); return () => clearTimeout(timer); }, [notice, copied]);
  const saveTask = async (draft: TaskDraft) => {
    if (mutationActive.current) throw new Error("Дождитесь завершения текущего сохранения.");
    mutationActive.current = true; setMutating(true); const version = ++requestVersion.current; setLoading(false);
    try { const next = await patchMediaProgramTask(adminToken, draft); if (requestVersion.current === version) setData(next); }
    catch (cause) { try { const next = await fetchMediaProgram(adminToken); if (requestVersion.current === version) setData(next); } catch { /* Retain the original save error and draft. */ } throw cause; }
    finally { mutationActive.current = false; setMutating(false); }
  };
  const saveChannel = async (draft: ChannelDraft) => {
    if (mutationActive.current) throw new Error("Дождитесь завершения текущего сохранения.");
    mutationActive.current = true; setMutating(true); const version = ++requestVersion.current; setLoading(false);
    try { const next = await patchMediaProgramChannel(adminToken, draft); if (requestVersion.current === version) setData(next); }
    catch (cause) { try { const next = await fetchMediaProgram(adminToken); if (requestVersion.current === version) setData(next); } catch { /* Retain the original save error and draft. */ } throw cause; }
    finally { mutationActive.current = false; setMutating(false); }
  };
  const selectTask = (id: string) => setUi((current) => ({ ...current, selected: id, view: current.view === "map" ? "map" : "tasks" }));
  const showTrack = (track: ProgramTrack | "all") => setUi((current) => ({ ...current, track, view: "tasks", status: "all", priority: "all", search: "" }));
  const filteredTasks = useMemo(() => (data?.tasks ?? []).filter((task) => (ui.track === "all" || task.track === ui.track) && (ui.status === "all" || task.status === ui.status) && (ui.priority === "all" || task.priority === ui.priority) && (!ui.search || `${task.id} ${task.title} ${task.description} ${task.owner}`.toLowerCase().includes(ui.search.toLowerCase()))), [data?.tasks, ui]);
  const selectedTask = data?.tasks.find((task) => task.id === ui.selected) ?? null;
  const copyContext = async () => { try { await navigator.clipboard.writeText(CONTEXT_PATH); setCopied(true); } catch { setNotice("Буфер обмена недоступен. Путь можно выделить и скопировать вручную."); } };
  if (!data) return <div className="growth-program"><div className="gp-card gp-loading" aria-live="polite">{loading ? <><Loader2 size={28} className="gp-spin" /><h2>Загружаем программу роста</h2><p>Задачи, каналы и сохранённый прогресс</p></> : <><ShieldAlert size={28} /><h2>Не удалось загрузить программу</h2><p role="alert">{error}</p><button className="gp-button gp-button-primary" type="button" onClick={() => void load()}><RefreshCw size={15} />Повторить</button></>}</div></div>;
  const summary = progress(data.tasks);
  const inProgress = data.tasks.filter((task) => task.status === "in_progress" || task.status === "review").length;
  const blocked = data.tasks.filter((task) => task.status === "blocked").length;
  const connected = data.channels.filter((channel) => channel.status === "connected").length;
  const phases = [...new Set(data.tasks.map((task) => task.phase))].sort((a, b) => a - b);
  const nextTasks = [...data.tasks].filter((task) => task.status !== "done").sort((a, b) => Number(a.status !== "blocked") - Number(b.status !== "blocked") || a.priority.localeCompare(b.priority) || a.phase - b.phase).slice(0, 4);
  const detail = <ProgramTaskDetail task={selectedTask} tasks={data.tasks} readOnly={!data.storage_ready} mutationPending={mutating} drafts={taskDrafts} setDrafts={setTaskDrafts} onSelect={selectTask} onSave={saveTask} onNavigateMedia={onNavigateMedia} />;
  return <div className="growth-program">
    <header className="gp-hero"><div className="gp-hero-copy"><span className="gp-eyebrow"><span className="gp-live-dot" />HAULZ · ПРОГРАММА РОСТА</span><h1>SEO <span>/</span> AEO <span>/</span> GEO</h1><p>От поисковой видимости к ответам ИИ.<br />Единая программа развития и автономного контент-завода.</p><div className="gp-hero-meta"><span><Network size={14} />6 направлений</span><span><ListChecks size={14} />{data.tasks.length} задач</span><span><BarChart3 size={14} />Встроенная аналитика</span></div></div><div className="gp-hero-right"><div className="gp-overall-ring"><svg viewBox="0 0 120 120" role="img" aria-label={`Выполнено ${summary.percent}% программы, ${summary.done} из ${summary.total} задач`}><circle cx="60" cy="60" r="51" className="gp-ring-track" /><circle cx="60" cy="60" r="51" className="gp-ring-fill" strokeDasharray={`${summary.percent * 3.2044} 320.44`} /></svg><div aria-hidden="true"><strong>{summary.percent}<small>%</small></strong><span>выполнено</span></div></div><span className="gp-hero-progress-label">{summary.done} из {summary.total} задач закрыто</span></div></header>
    <div className="gp-toolbar"><span className="gp-muted gp-sync-state"><span className={`gp-sync-dot ${data.storage_ready ? "is-ready" : ""}`} />{data.storage_ready ? `Состояние на ${formatDate(data.updated_at)}` : "Предпросмотр программы · только чтение"}</span><div className="gp-actions"><button className="gp-button" type="button" onClick={() => { exportContext(data); setNotice("Снимок состояния выгружен в Markdown"); }}><Download size={15} />Экспорт состояния</button><button className="gp-icon-button" type="button" onClick={() => void load()} disabled={loading || mutating} aria-label="Обновить программу" title="Обновить программу"><RefreshCw size={17} className={loading ? "gp-spin" : ""} /></button></div></div>
    {!data.storage_ready && <div className="gp-notice gp-notice-warning" role="status"><ShieldAlert size={19} /><div><strong>Хранилище программы ещё не готово</strong><p>{data.setup_message || "Сейчас доступен просмотр стартового плана. Сохранение задач и каналов появится после настройки базы данных."}</p></div></div>}
    {error && <div className="gp-notice gp-notice-error" role="alert"><ShieldAlert size={18} /><span>{error}</span><button className="gp-button" type="button" disabled={loading || mutating} onClick={() => void load()}>Повторить</button></div>}
    {notice && <div className="gp-notice" role="status">{notice}</div>}
    <section className="gp-kpis" aria-label="Показатели программы"><div className="gp-card gp-kpi"><span><CheckCircle2 size={17} />Завершено</span><strong>{summary.done}<small> / {summary.total}</small></strong><div className="gp-progress"><span style={{ width: `${summary.percent}%` }} /></div></div><div className="gp-card gp-kpi"><span><Layers3 size={17} />В работе и на проверке</span><strong>{inProgress}</strong><small>Активные задачи команды</small></div><button type="button" className="gp-card gp-kpi gp-kpi-button" onClick={() => setUi((current) => ({ ...current, view: "tasks", status: "blocked", track: "all", priority: "all", search: "" }))}><span><Flag size={17} />Блокировки<ArrowUpRight size={14} /></span><strong className={blocked ? "gp-warning-text" : ""}>{blocked}</strong><small>{blocked ? "Требуют решения" : "Нет отмеченных блокировок"}</small></button><button type="button" className="gp-card gp-kpi gp-kpi-button" onClick={() => setUi((current) => ({ ...current, view: "channels" }))}><span><Target size={17} />Готовность каналов<ArrowUpRight size={14} /></span><strong>{connected}<small> / {data.channels.length}</small></strong><small>По данным ручного реестра</small></button></section>
    <nav className="gp-tabs" aria-label="Разделы программы">{VIEWS.map((view) => <button type="button" key={view.id} onClick={() => setUi((current) => ({ ...current, view: view.id }))} className={ui.view === view.id ? "is-active" : ""} aria-current={ui.view === view.id ? "page" : undefined}>{view.label}{view.id === "tasks" && <span>{data.tasks.length}</span>}</button>)}</nav>
    {ui.view === "overview" && <div className="gp-overview">
      <div className="gp-overview-main"><section className="gp-card gp-track-card"><div className="gp-section-heading"><div><span className="gp-eyebrow">EXECUTION</span><h2>Прогресс по направлениям</h2><p>Фактическое состояние задач программы</p></div><button type="button" className="gp-icon-button" onClick={() => setUi((current) => ({ ...current, view: "map" }))} aria-label="Открыть карту программы"><Network size={18} /></button></div><div className="gp-track-list">{TRACKS.map((track) => { const tasks = data.tasks.filter((task) => task.track === track.id); const stats = progress(tasks); return <button type="button" className="gp-track-row" key={track.id} onClick={() => showTrack(track.id)}><div className="gp-track-row-label"><span className="gp-track-symbol" style={{ background: `${track.color}1f`, color: track.color }}>{track.short.slice(0, 3)}</span><span><strong>{track.label}</strong><small>{track.description}</small></span><b>{stats.percent}%</b><ArrowUpRight size={14} /></div><div className="gp-stacked-bar" role="img" aria-label={`${track.label}: ${stats.done} из ${stats.total} задач готово`}>{STATUS_ORDER.map((status) => { const count = tasks.filter((task) => task.status === status).length; return count > 0 && <span key={status} className={`gp-status-${status}`} title={`${STATUS[status]}: ${count}`} style={{ width: `${count / tasks.length * 100}%` }} />; })}</div><span className="gp-track-count">{stats.done} / {stats.total} задач выполнено</span></button>; })}</div><div className="gp-chart-legend">{STATUS_ORDER.map((status) => <span key={status}><i className={`gp-status-${status}`} />{STATUS[status]}</span>)}</div></section>
        <section className="gp-card"><div className="gp-section-heading"><div><span className="gp-eyebrow">ROADMAP</span><h2>Последовательность запуска</h2><p>Этапы показывают готовность работ, а не прогноз сроков</p></div></div><div className="gp-phases">{phases.map((phase) => { const tasks = data.tasks.filter((task) => task.phase === phase); const stats = progress(tasks); return <div className="gp-phase" key={phase}><span className={`gp-phase-marker ${stats.percent === 100 ? "is-done" : ""}`}>{stats.percent === 100 ? <Check size={16} /> : phase}</span><div><strong>Этап {phase}</strong><span>{stats.done} из {stats.total} задач</span><div className="gp-progress"><span style={{ width: `${stats.percent}%` }} /></div></div></div>; })}</div></section>
        <section className="gp-card gp-analytics"><div className="gp-section-heading"><div><span className="gp-eyebrow">MEASUREMENT</span><h2>Результаты продвижения</h2><p>Материалы — из медиаплана; внешние метрики — после подключения источников</p></div><BarChart3 size={22} /></div><div className="gp-metrics-grid">{data.metrics.map((metric) => <div key={metric.key}><span>{metric.label}</span><strong>{metric.value === null ? "—" : metric.value.toLocaleString("ru-RU")}</strong><small>{metric.note || (metric.value === null ? "Нет данных" : "Данные источника")}</small></div>)}</div>{data.metrics.every((metric) => metric.value === null) && <div className="gp-metrics-note"><Activity size={15} />Трафик, упоминания ИИ и конверсии пока не измеряются. Прогресс работ показан выше.</div>}</section>
      </div><div className="gp-overview-side"><section className="gp-card gp-focus-card"><div className="gp-section-heading"><div><span className="gp-eyebrow">NEXT ACTIONS</span><h2>В фокусе команды</h2></div><Flag size={19} /></div><div className="gp-next-tasks">{nextTasks.map((task, index) => <button type="button" key={task.id} onClick={() => selectTask(task.id)}><span className="gp-next-number">{String(index + 1).padStart(2, "0")}</span><span><small>{task.id} · {task.priority} · {STATUS[task.status]}</small><strong>{task.title}</strong><span>{task.owner || "Ответственный не назначен"}</span></span><ArrowRight size={15} /></button>)}{!nextTasks.length && <div className="gp-empty gp-empty-small"><CheckCircle2 size={24} /><p>Все задачи программы завершены</p></div>}</div></section>
        <section className="gp-card gp-context-card"><BookOpen size={22} /><span className="gp-eyebrow">LONG-TERM CONTEXT</span><h2>Контекст программы</h2><p>Стратегия, принятые решения и правила продолжения работы — в одном документе.</p><div className="gp-context-path"><code>{CONTEXT_PATH}</code><button type="button" className="gp-icon-button" onClick={() => void copyContext()} title="Скопировать путь" aria-label="Скопировать путь к контексту">{copied ? <Check size={14} /> : <Copy size={14} />}</button></div><button type="button" className="gp-button" onClick={() => downloadProgramDocument()}><Download size={15} />Скачать контекст</button><button type="button" className="gp-button gp-button-quiet" onClick={() => downloadProgramDocument(true)}>Полный план программы<ArrowUpRight size={14} /></button><small>Текущее состояние задач и каналов выгружается кнопкой «Экспорт состояния».</small></section>
        <section className="gp-card"><div className="gp-section-heading"><div><span className="gp-eyebrow">ACTIVITY</span><h2>Последние изменения</h2></div></div><ActivityList activity={data.activity.slice(0, 4)} tasks={data.tasks} onSelect={selectTask} />{data.activity.length > 4 && <button type="button" className="gp-button gp-button-quiet" onClick={() => setUi((current) => ({ ...current, view: "activity" }))}>Вся история<ArrowRight size={14} /></button>}</section>
      </div>
    </div>}
    {ui.view === "map" && <div className={`gp-workspace ${selectedTask ? "has-detail" : ""}`}><ProgramMap tasks={data.tasks} track={ui.track} selectedId={ui.selected} onTrack={(track) => setUi((current) => ({ ...current, track }))} onSelect={selectTask} />{selectedTask && detail}</div>}
    {ui.view === "tasks" && <div className="gp-workspace has-detail"><section className="gp-card gp-task-list-card"><div className="gp-section-heading"><div><span className="gp-eyebrow">WORKSPACE</span><h2>Чек-лист программы</h2><p>{filteredTasks.length} из {data.tasks.length} задач · {data.storage_ready ? "изменения сохраняются на сервере" : "доступен просмотр"}</p></div></div><div className="gp-filters"><label className="gp-search"><Search size={16} /><input value={ui.search} onChange={(event) => setUi((current) => ({ ...current, search: event.target.value }))} placeholder="Найти задачу или ответственного" aria-label="Поиск задач" /></label><div><label>Направление<select value={ui.track} onChange={(event) => setUi((current) => ({ ...current, track: event.target.value as ProgramTrack | "all" }))}><option value="all">Все направления</option>{TRACKS.map((track) => <option key={track.id} value={track.id}>{track.label}</option>)}</select></label><label>Статус<select value={ui.status} onChange={(event) => setUi((current) => ({ ...current, status: event.target.value as ProgramTaskStatus | "all" }))}><option value="all">Все статусы</option>{Object.entries(STATUS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Приоритет<select value={ui.priority} onChange={(event) => setUi((current) => ({ ...current, priority: event.target.value }))}><option value="all">Все</option>{["P0", "P1", "P2", "P3"].map((priority) => <option value={priority} key={priority}>{priority}</option>)}</select></label></div></div><div className="gp-task-list">{filteredTasks.map((task) => <button type="button" key={task.id} className={`gp-task-row ${ui.selected === task.id ? "is-selected" : ""}`} onClick={() => selectTask(task.id)} aria-pressed={ui.selected === task.id}><span className={`gp-task-check gp-status-${task.status}`}>{task.status === "done" ? <Check size={13} /> : task.status === "blocked" ? "!" : ""}</span><span className="gp-task-row-content"><strong><code className="gp-inline-id">{task.id}</code>{task.title}</strong><span className="gp-task-row-meta"><span>{TRACKS.find((track) => track.id === task.track)?.label}</span><span>Этап {task.phase}</span><span>{task.owner || "Без ответственного"}</span></span><span className={`gp-status-label gp-status-${task.status}`}>{STATUS[task.status]}</span></span><span className={`gp-priority gp-priority-${task.priority.toLowerCase()}`}>{task.priority}</span><ArrowUpRight size={14} /></button>)}{!filteredTasks.length && <div className="gp-empty"><Search size={27} /><h3>Задачи не найдены</h3><p>Попробуйте изменить поиск или фильтры.</p><button type="button" className="gp-button" onClick={() => setUi((current) => ({ ...current, search: "", track: "all", status: "all", priority: "all" }))}>Сбросить фильтры</button></div>}</div></section>{detail}</div>}
    {ui.view === "channels" && <ProgramChannels channels={data.channels} readOnly={!data.storage_ready} mutationPending={mutating} drafts={channelDrafts} setDrafts={setChannelDrafts} onSave={saveChannel} />}
    {ui.view === "activity" && <section className="gp-card gp-history-card"><div className="gp-section-heading"><div><span className="gp-eyebrow">AUDIT TRAIL</span><h2>История программы</h2><p>Последние сохранённые изменения задач и каналов</p></div></div><ActivityList activity={data.activity} tasks={data.tasks} onSelect={selectTask} /></section>}
  </div>;
}
