import React,{useEffect,useState} from 'react';
import {adminAuthHeaders} from '../../../api/client/admin/auth';
type QueueData={facts:{id:string;claim:string;status:string;valid_until?:string}[];jobs:{id:number;revision:number;kind:string;state:string;reasons:string[];result_revision:number|null;fact_pack:{sources:{reference:string;state:string}[]}}[];attempts:{id:number;job_id:number;state:string;provider_started:boolean;input_tokens:number|null;output_tokens:number|null;estimated_usd:string|null;reserved_usd:string}[];settings:{generation_enabled:boolean;daily_budget_usd:string}};
const states:Record<string,string>={queued:'В очереди',running:'В работе',held:'Удержано',done:'Готово'};
export function MediaFactoryQueue({adminToken,id,revision,dirty,onChanged}:{adminToken:string;id:number;revision:number;dirty:boolean;onChanged:()=>unknown}){
 const [data,setData]=useState<QueueData|null>(null),[ids,setIds]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const headers={...adminAuthHeaders(adminToken),'Content-Type':'application/json'};
 async function read(){const r=await fetch(`/api/admin-content-factory?id=${id}`,{headers});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{setIds([]);read().catch(e=>setError(e.message));},[id,revision]);
 async function action(body:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch('/api/admin-content-factory',{method:'POST',headers,body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);await read();onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section aria-label="Источники и очередь" style={{border:'1px solid var(--color-border)',padding:16,borderRadius:12,margin:'20px 0'}}>
  <h4>Источники и очередь</h4><p>Выберите факты, на которые опирается материал. Проверка сверяет актуальность и версии источников, ищет рискованные обещания и точные дубли. Смысл текста и полноту фактов проверяет редактор перед публикацией.</p>
  {error&&<p role="alert">{error}</p>}
  {data&&<><p>{data.settings.generation_enabled?`Лимит генерации: $${data.settings.daily_budget_usd} в сутки (UTC).`:'Платная генерация выключена. Проверка источников доступна бесплатно.'}</p>
  <details><summary>Выбрать факты ({ids.length})</summary>{data.facts.map(f=>{const allowed=['owner_confirmed','code_verified'].includes(f.status)&&!!f.valid_until&&Date.parse(f.valid_until)>Date.now();return <label key={f.id} style={{display:'block',margin:'8px 0'}}><input type="checkbox" disabled={busy||!allowed} checked={ids.includes(f.id)} onChange={e=>setIds(e.target.checked?[...ids,f.id]:ids.filter(x=>x!==f.id))}/> {f.claim} <small>({f.id}; {allowed?`проверка до ${f.valid_until}`:'нужно подтверждение'})</small></label>;})}</details>
  <p style={{display:'flex',gap:8,flexWrap:'wrap'}}><button type="button" className="filter-button" disabled={busy||dirty||!ids.length} onClick={()=>action({action:'enqueue',kind:'check',id,expected_revision:revision,fact_ids:ids})}>Поставить проверку в очередь</button><button type="button" className="filter-button" disabled={busy||dirty||!ids.length||!data.settings.generation_enabled} onClick={()=>action({action:'enqueue',kind:'generate',id,expected_revision:revision,fact_ids:ids})}>Поставить генерацию в очередь</button><button type="button" className="filter-button" disabled={busy||dirty} onClick={()=>action({action:'run'})}>Обработать следующее задание</button><button type="button" className="filter-button" disabled={busy} onClick={()=>read().catch(e=>setError(e.message))}>Обновить очередь</button></p>
  <p>Одновременно обрабатывается одно задание общей очереди. Готовая генерация сохраняется только в черновик; затем нужна отдельная проверка новой версии.</p>
  {!data.jobs.length&&<p>Заданий пока нет.</p>}
  {data.jobs.map(j=><article key={j.id} style={{borderTop:'1px solid var(--color-border)',padding:'12px 0'}}><strong>№{j.id} · {j.kind==='check'?'Проверка':'Генерация'} · версия {j.revision} · {states[j.state]||j.state}</strong>{j.reasons.map((r,i)=><p key={i}>{r}</p>)}{j.result_revision&&<p>Сохранено в черновик версии {j.result_revision}. Обновите материал с сервера.</p>}<details><summary>Источники и попытки</summary>{j.fact_pack.sources.map((s,i)=><p key={i}>{s.reference}: {s.state}</p>)}{data.attempts.filter(a=>a.job_id===j.id).map(a=><p key={a.id}>Попытка {a.id}: {a.state}; {a.provider_started?`токены ${a.input_tokens??'неизвестно'} / ${a.output_tokens??'неизвестно'}; оценка по настроенному тарифу: ${a.estimated_usd===null?'неизвестна':'$'+a.estimated_usd}; резерв $${a.reserved_usd}`:'модель не вызывалась, расход $0'}.</p>)}</details>{j.state==='held'&&j.revision===revision&&!data.attempts.some(a=>a.job_id===j.id&&a.provider_started)&&<button type="button" className="filter-button" disabled={busy||dirty} onClick={()=>action({action:'retry',job_id:j.id})}>Повторить после исправления причины</button>}</article>)}</>}
 </section>;
}
